theme: jekyll-theme-midnight
gems:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-gist
  - jekyll-feed
timezone: America/New_York
future: true
paginate: 50
excerpt_separator: <!--more-->
url: https://blog.mcguirev10.com
title: "Jon McGuire"
description: "Forty Years of Coding"

# Everthing below forces line-numbering in code blocks per > https://github.com/jekyll/jekyll/issues/4619#issuecomment-191267346
# !github-pages! mandatory › https://help.github.com/articles/configuring-jekyll/#configuration-settings-you-cannot-change

markdown: kramdown
# More › http://kramdown.gettalong.org/quickref.html
# Options › http://kramdown.gettalong.org/options.html
kramdown:
  # Rouge Highlighter in Kramdown › http://kramdown.gettalong.org/syntax_highlighter/rouge.html
  syntax_highlighter_opts:
    # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1