remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "dark"

gems:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-gist
  - jekyll-feed

timezone: America/New_York
future: true
paginate: 10
excerpt_separator: <!--more-->

url: https://blog.mcguirev10.com
title: Forty Years of Code
name: Jon McGuire
description: "A developer blog about C#, .NET, Azure, Unity games, and other topics"
teaser: /assets/images/index_header.jpg

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author: true
      author_profile: true
      toc: true
      comments: true
      share: true
      related: true

author:
  name   : Jon McGuire
  avatar : "/assets/images/headshot.jpg"
  bio    : "All ya gotta do is..."

comments:
  provider: "disqus"
  disqus:
    shortname: "mv10"

# everything below forces line-numbering in code blocks per > https://github.com/jekyll/jekyll/issues/4619#issuecomment-191267346
markdown: kramdown
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    default_lang: csharp
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: true
